spring:
  application:
    name: temperatura-converter-service

server:
  port: 9001
  servlet:
    context-path: /temperatura

management:
  server:
    base-path: /temperatura/actuator
  endpoints:
    web:
      exposure:
        include: '*'
